a = input("enter your name: ")
b = input("enter your age:  ")
c = input("enter city where you live: ")
print("Hello," + " " + a)
print("You are" + " " + b + " " + "years old")
print ("You live in" + " " + c)