a = int(input("enter a\n"))
b = int(input("enter b\n"))
a1 = a+b
a2 = a-b
a3 = a*b
a4 = a/b
a5 = a//b
a6 = a%b
a7 = a**b
print (a, '+', b, '=',a1)
print (a, '-', b, '=',a2)
print (a, '*', b, '=',a3)
print (a, '/', b, '=',a4)
print (a, '//', b, '=',a5)
print (a, '%', b, '=',a6)
print (a, '**', b, '=',a7)